[0m12:11:24.436112 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDC74ED50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDC722C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDC74E950>]}


============================== 12:11:24.453696 | f389c715-1c15-47a1-a6de-984b91a8cf5a ==============================
[0m12:11:24.453696 [info ] [MainThread]: Running with dbt=1.6.17
[0m12:11:24.462193 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt deps', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:11:24.467180 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\fajlh\OneDrive\Documents\DBT_demo\DBT_demo\Dummy_generated\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:11:24.476155 [debug] [MainThread]: Command `dbt deps` failed at 12:11:24.475159 after 0.11 seconds
[0m12:11:24.478152 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDC7AFD50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDCFE3F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028FDC48ACD0>]}
[0m12:11:24.480143 [debug] [MainThread]: Flushing usage events
[0m12:15:27.218171 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B6C453D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B6822850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B636C6D0>]}


============================== 12:15:27.231417 | 6a5bd739-955a-4728-acbd-10d454c46d16 ==============================
[0m12:15:27.231417 [info ] [MainThread]: Running with dbt=1.6.17
[0m12:15:27.234407 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:15:27.405449 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B660B710>]}
[0m12:15:27.415461 [debug] [MainThread]: Set downloads directory='C:\Users\fajlh\AppData\Local\Temp\dbt-downloads-5ne8aui7'
[0m12:15:27.420452 [debug] [MainThread]: Making package index registry request: GET https://hub.getdbt.com/api/v1/index.json
[0m12:15:27.592017 [debug] [MainThread]: Response from registry index: GET https://hub.getdbt.com/api/v1/index.json 200
[0m12:15:27.595009 [debug] [MainThread]: Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json
[0m12:15:27.713486 [debug] [MainThread]: Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json 200
[0m12:15:27.721465 [debug] [MainThread]: Making package registry request: GET https://hub.getdbt.com/api/v1/calogica/dbt_expectations.json
[0m12:15:39.201401 [debug] [MainThread]: Response from registry: GET https://hub.getdbt.com/api/v1/calogica/dbt_expectations.json 200
[0m12:15:39.215363 [debug] [MainThread]: Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/codegen.json
[0m12:15:39.338034 [debug] [MainThread]: Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/codegen.json 200
[0m12:15:39.345015 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt_faker.git 979d311c388461b63a6e869ef41cb439"
[0m12:15:41.187237 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:41.188235 [debug] [MainThread]: STDERR: "b"Cloning into '979d311c388461b63a6e869ef41cb439'...\n""
[0m12:15:41.189232 [debug] [MainThread]: Pulling new dependency 979d311c388461b63a6e869ef41cb439.
[0m12:15:41.190231 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:15:41.237742 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:15:41.238735 [debug] [MainThread]: STDERR: "b''"
[0m12:15:41.239732 [debug] [MainThread]: Checking out revision main.
[0m12:15:41.240731 [debug] [MainThread]: Executing "git remote set-branches origin main"
[0m12:15:41.283560 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:41.284558 [debug] [MainThread]: STDERR: "b''"
[0m12:15:41.285555 [debug] [MainThread]: Executing "git fetch origin --depth 1 --tags main"
[0m12:15:42.670118 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:42.671118 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt_faker\n * branch            main       -> FETCH_HEAD\n'"
[0m12:15:42.672116 [debug] [MainThread]: Executing "git tag --list"
[0m12:15:42.704962 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:42.705958 [debug] [MainThread]: STDERR: "b''"
[0m12:15:42.706956 [debug] [MainThread]: Executing "git reset --hard origin/main"
[0m12:15:42.765356 [debug] [MainThread]: STDOUT: "b'HEAD is now at 72562f8 Merge pull request #27 from Datateer/support-faker-provider-parameters\n'"
[0m12:15:42.768349 [debug] [MainThread]: STDERR: "b''"
[0m12:15:42.769346 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:15:42.804253 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:15:42.806261 [debug] [MainThread]: STDERR: "b''"
[0m12:15:42.807246 [debug] [MainThread]: Checked out at 72562f8.
[0m12:15:42.809240 [warn ] [MainThread]: [33mWARNING: The git package "https://github.com/dbt-labs/dbt_faker.git" 
	is None.
	This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions[0m
[0m12:15:42.824114 [debug] [MainThread]: Making package registry request: GET https://hub.getdbt.com/api/v1/calogica/dbt_date.json
[0m12:15:42.933095 [debug] [MainThread]: Response from registry: GET https://hub.getdbt.com/api/v1/calogica/dbt_date.json 200
[0m12:15:42.974983 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt_faker.git 979d311c388461b63a6e869ef41cb439"
[0m12:15:43.070726 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:43.072724 [debug] [MainThread]: STDERR: "b"fatal: destination path '979d311c388461b63a6e869ef41cb439' already exists and is not an empty directory.\n""
[0m12:15:43.074716 [debug] [MainThread]: command return code=128
[0m12:15:43.078704 [debug] [MainThread]: Updating existing dependency 979d311c388461b63a6e869ef41cb439.
[0m12:15:43.081697 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:15:43.120593 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:15:43.122587 [debug] [MainThread]: STDERR: "b''"
[0m12:15:43.124591 [debug] [MainThread]: Checking out revision main.
[0m12:15:43.125580 [debug] [MainThread]: Executing "git remote set-branches origin main"
[0m12:15:43.169513 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:43.170509 [debug] [MainThread]: STDERR: "b''"
[0m12:15:43.171507 [debug] [MainThread]: Executing "git fetch origin --depth 1 --tags main"
[0m12:15:44.562240 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:44.562240 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt_faker\n * branch            main       -> FETCH_HEAD\n'"
[0m12:15:44.564235 [debug] [MainThread]: Executing "git tag --list"
[0m12:15:44.597145 [debug] [MainThread]: STDOUT: "b''"
[0m12:15:44.597145 [debug] [MainThread]: STDERR: "b''"
[0m12:15:44.598145 [debug] [MainThread]: Executing "git reset --hard origin/main"
[0m12:15:44.645278 [debug] [MainThread]: STDOUT: "b'HEAD is now at 72562f8 Merge pull request #27 from Datateer/support-faker-provider-parameters\n'"
[0m12:15:44.647270 [debug] [MainThread]: STDERR: "b''"
[0m12:15:44.648268 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:15:44.676192 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:15:44.677190 [debug] [MainThread]: STDERR: "b''"
[0m12:15:44.678188 [debug] [MainThread]: Already at 72562f8, nothing to do.
[0m12:15:44.680182 [warn ] [MainThread]: [33mWARNING: The git package "https://github.com/dbt-labs/dbt_faker.git" 
	is None.
	This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions[0m
[0m12:15:44.684173 [info ] [MainThread]: Installing dbt-labs/dbt_utils
[0m12:15:55.391403 [info ] [MainThread]: Installed from version 1.0.0
[0m12:15:55.394395 [info ] [MainThread]: Updated version available: 1.2.0
[0m12:15:55.396390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'package', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'property_': 'install', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B68361D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B636C250>]}
[0m12:15:55.398386 [info ] [MainThread]: Installing calogica/dbt_expectations
[0m12:16:06.506571 [info ] [MainThread]: Installed from version 0.8.5
[0m12:16:06.508563 [info ] [MainThread]: Updated version available: 0.10.3
[0m12:16:06.510557 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'package', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'property_': 'install', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B729F650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B729DE10>]}
[0m12:16:06.512553 [info ] [MainThread]: Installing dbt-labs/codegen
[0m12:16:16.927808 [info ] [MainThread]: Installed from version 0.9.0
[0m12:16:16.931797 [info ] [MainThread]: Updated version available: 0.12.1
[0m12:16:16.933792 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'package', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'property_': 'install', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B722DB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B722E750>]}
[0m12:16:16.935786 [info ] [MainThread]: Installing https://github.com/dbt-labs/dbt_faker.git
[0m12:16:16.938778 [debug] [MainThread]: Executing "git clone --depth 1 https://github.com/dbt-labs/dbt_faker.git 979d311c388461b63a6e869ef41cb439"
[0m12:16:17.003605 [debug] [MainThread]: STDOUT: "b''"
[0m12:16:17.004603 [debug] [MainThread]: STDERR: "b"fatal: destination path '979d311c388461b63a6e869ef41cb439' already exists and is not an empty directory.\n""
[0m12:16:17.005600 [debug] [MainThread]: command return code=128
[0m12:16:17.008591 [debug] [MainThread]: Updating existing dependency 979d311c388461b63a6e869ef41cb439.
[0m12:16:17.010586 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:16:17.064442 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:16:17.065439 [debug] [MainThread]: STDERR: "b''"
[0m12:16:17.066438 [debug] [MainThread]: Checking out revision main.
[0m12:16:17.067434 [debug] [MainThread]: Executing "git remote set-branches origin main"
[0m12:16:17.139242 [debug] [MainThread]: STDOUT: "b''"
[0m12:16:17.140240 [debug] [MainThread]: STDERR: "b''"
[0m12:16:17.142234 [debug] [MainThread]: Executing "git fetch origin --depth 1 --tags main"
[0m12:16:18.593184 [debug] [MainThread]: STDOUT: "b''"
[0m12:16:18.595178 [debug] [MainThread]: STDERR: "b'From https://github.com/dbt-labs/dbt_faker\n * branch            main       -> FETCH_HEAD\n'"
[0m12:16:18.596176 [debug] [MainThread]: Executing "git tag --list"
[0m12:16:18.635343 [debug] [MainThread]: STDOUT: "b''"
[0m12:16:18.636339 [debug] [MainThread]: STDERR: "b''"
[0m12:16:18.638332 [debug] [MainThread]: Executing "git reset --hard origin/main"
[0m12:16:18.696177 [debug] [MainThread]: STDOUT: "b'HEAD is now at 72562f8 Merge pull request #27 from Datateer/support-faker-provider-parameters\n'"
[0m12:16:18.697174 [debug] [MainThread]: STDERR: "b''"
[0m12:16:18.698172 [debug] [MainThread]: Executing "git rev-parse HEAD"
[0m12:16:18.730087 [debug] [MainThread]: STDOUT: "b'72562f846f83cb8b483a5d5d151d7ae31ba3a465\n'"
[0m12:16:18.730087 [debug] [MainThread]: STDERR: "b''"
[0m12:16:18.731084 [debug] [MainThread]: Already at 72562f8, nothing to do.
[0m12:16:18.742056 [info ] [MainThread]: Installed from revision main
[0m12:16:18.744053 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'package', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'property_': 'install', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B720F150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B72CF010>]}
[0m12:16:18.746047 [info ] [MainThread]: Installing calogica/dbt_date
[0m12:16:29.097422 [info ] [MainThread]: Installed from version 0.7.2
[0m12:16:29.099416 [info ] [MainThread]: Updated version available: 0.10.1
[0m12:16:29.101411 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'package', 'label': '6a5bd739-955a-4728-acbd-10d454c46d16', 'property_': 'install', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B72CC810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B72CD4D0>]}
[0m12:16:29.102408 [info ] [MainThread]: 
[0m12:16:29.104403 [info ] [MainThread]: Updates available for packages: ['dbt-labs/dbt_utils', 'calogica/dbt_expectations', 'dbt-labs/codegen', 'calogica/dbt_date']                 
Update your versions in packages.yml, then run dbt deps
[0m12:16:29.111385 [debug] [MainThread]: Command `dbt deps` succeeded at 12:16:29.111385 after 61.94 seconds
[0m12:16:29.113378 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B660A310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B6EE9850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215B6EFDC10>]}
[0m12:16:29.114376 [debug] [MainThread]: Flushing usage events
[0m13:21:16.024627 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2BEAA390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2C813CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2C534C10>]}


============================== 13:21:16.117379 | 5aa5597d-9085-412b-a7af-8547d563e42c ==============================
[0m13:21:16.117379 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:21:16.120372 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run-operation generate_faker_model', 'send_anonymous_usage_stats': 'True'}
[0m13:21:21.186529 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2DCADE50>]}
[0m13:21:21.242382 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2D5E13D0>]}
[0m13:21:21.249362 [info ] [MainThread]: Registered adapter: bigquery=1.6.1
[0m13:21:21.421900 [debug] [MainThread]: checksum: 5068fe71dce20d17d52958fa9cd93ea8f20705f4dc29725ea3e5886531e90d9e, vars: {}, profile: , target: , version: 1.6.17
[0m13:21:21.519641 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m13:21:21.521634 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2DF03C90>]}
[0m13:21:26.764011 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.answers.marts
- models.answers
- tests.answers
[0m13:21:26.795925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2AC12990>]}
[0m13:21:26.867731 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2DF3A650>]}
[0m13:21:26.869726 [info ] [MainThread]: Found 1 operation, 1 source, 0 exposures, 0 metrics, 744 macros, 0 groups, 0 semantic models
[0m13:21:26.871723 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '5aa5597d-9085-412b-a7af-8547d563e42c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2DCB13D0>]}
[0m13:21:26.874712 [debug] [MainThread]: Acquiring new bigquery connection 'macro_generate_faker_model'
[0m13:21:26.930564 [info ] [MainThread]: dbt_faker appended to `configured_sources`: source.Dummy_generated.fake_tpch.orders
[0m13:21:26.934554 [info ] [MainThread]: dbt_faker has some sources to fake!
[0m13:21:27.047252 [debug] [MainThread]: Command `dbt run-operation` succeeded at 13:21:27.047252 after 11.10 seconds
[0m13:21:27.049246 [debug] [MainThread]: Connection 'macro_generate_faker_model' was properly closed.
[0m13:21:27.050244 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2BE870D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A25C93AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028A2BEB0510>]}
[0m13:21:27.052237 [debug] [MainThread]: Flushing usage events
[0m13:25:50.598085 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002287780A410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228769BE610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228769BF250>]}


============================== 13:25:50.603076 | e161aa5e-e70c-468a-a6f5-c6cfceff0cc6 ==============================
[0m13:25:50.603076 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:25:50.604990 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run -m dbt_faker.py', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:25:51.225361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'e161aa5e-e70c-468a-a6f5-c6cfceff0cc6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022878510710>]}
[0m13:25:51.251258 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'e161aa5e-e70c-468a-a6f5-c6cfceff0cc6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002287721B650>]}
[0m13:25:51.253253 [info ] [MainThread]: Registered adapter: bigquery=1.6.1
[0m13:25:51.337029 [debug] [MainThread]: checksum: 5068fe71dce20d17d52958fa9cd93ea8f20705f4dc29725ea3e5886531e90d9e, vars: {}, profile: , target: , version: 1.6.17
[0m13:25:51.563642 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:25:51.563642 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:25:51.564610 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.answers.marts
- models.answers
- tests.answers
[0m13:25:51.572618 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'e161aa5e-e70c-468a-a6f5-c6cfceff0cc6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228784D8A10>]}
[0m13:25:51.609491 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'e161aa5e-e70c-468a-a6f5-c6cfceff0cc6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022878CCF0D0>]}
[0m13:25:51.611485 [info ] [MainThread]: Found 1 operation, 1 source, 0 exposures, 0 metrics, 744 macros, 0 groups, 0 semantic models
[0m13:25:51.612482 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'e161aa5e-e70c-468a-a6f5-c6cfceff0cc6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022872222790>]}
[0m13:25:51.614476 [warn ] [MainThread]: The selection criterion 'dbt_faker.py' does not match any nodes
[0m13:25:51.617468 [info ] [MainThread]: 
[0m13:25:51.619464 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:25:51.622455 [debug] [MainThread]: Command end result
[0m13:25:51.672325 [debug] [MainThread]: Command `dbt run` succeeded at 13:25:51.672325 after 1.11 seconds
[0m13:25:51.673319 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022876C65150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022876962990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022871293950>]}
[0m13:25:51.677313 [debug] [MainThread]: Flushing usage events
[0m13:38:27.216969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C0070A4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BFFE0E610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BFFF1F450>]}


============================== 13:38:27.231392 | 5c8c2d80-26e4-4428-a805-b7a1129ac093 ==============================
[0m13:38:27.231392 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:38:27.233384 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run -m dbt_faker.py', 'send_anonymous_usage_stats': 'True'}
[0m13:38:27.239368 [error] [MainThread]: Encountered an error:
Runtime Error
  The profile 'Dummy_generated' does not have a target named 'test'. The valid target names for this profile are:
   - dev
[0m13:38:27.242362 [debug] [MainThread]: Command `dbt run` failed at 13:38:27.242362 after 0.09 seconds
[0m13:38:27.243359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C007077D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BFFC65150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022BFFC47290>]}
[0m13:38:27.245354 [debug] [MainThread]: Flushing usage events
[0m13:39:39.019958 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F7D089D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F78F7D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F7862A10>]}


============================== 13:39:39.024948 | 510d07f7-27d5-45cd-b149-16f82e0af913 ==============================
[0m13:39:39.024948 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:39:39.026942 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run -m dbt_faker.py', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:39:39.032926 [error] [MainThread]: Encountered an error:
Runtime Error
  The profile 'Dummy_generated' does not have a target named 'testing'. The valid target names for this profile are:
   - dev
[0m13:39:39.036220 [debug] [MainThread]: Command `dbt run` failed at 13:39:39.036220 after 0.06 seconds
[0m13:39:39.037217 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F6FBF0D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F1813710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000196F746D150>]}
[0m13:39:39.039212 [debug] [MainThread]: Flushing usage events
[0m13:40:38.357250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F4607D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F3D15DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F3D6CB90>]}


============================== 13:40:38.362237 | 54be6605-f280-47c0-adca-a479794fd16d ==============================
[0m13:40:38.362237 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:40:38.364232 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -m dbt_faker.py', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:40:39.150362 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F5324110>]}
[0m13:40:39.171334 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F3B641D0>]}
[0m13:40:39.174296 [info ] [MainThread]: Registered adapter: bigquery=1.6.1
[0m13:40:39.255229 [debug] [MainThread]: checksum: 5068fe71dce20d17d52958fa9cd93ea8f20705f4dc29725ea3e5886531e90d9e, vars: {}, profile: , target: , version: 1.6.17
[0m13:40:39.286112 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m13:40:39.287109 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F5C69D90>]}
[0m13:40:42.032796 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.answers
- models.answers.marts
- tests.answers
[0m13:40:42.042768 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F5C5E810>]}
[0m13:40:42.092636 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F5BAA8D0>]}
[0m13:40:42.093633 [info ] [MainThread]: Found 1 operation, 1 source, 0 exposures, 0 metrics, 744 macros, 0 groups, 0 semantic models
[0m13:40:42.095628 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '54be6605-f280-47c0-adca-a479794fd16d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F52DEB90>]}
[0m13:40:42.098625 [warn ] [MainThread]: The selection criterion 'dbt_faker.py' does not match any nodes
[0m13:40:42.103607 [info ] [MainThread]: 
[0m13:40:42.105601 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:40:42.108593 [debug] [MainThread]: Command end result
[0m13:40:42.153473 [debug] [MainThread]: Command `dbt run` succeeded at 13:40:42.153473 after 3.84 seconds
[0m13:40:42.157464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F3A93490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F5AF9810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188F401BCD0>]}
[0m13:40:42.159457 [debug] [MainThread]: Flushing usage events
[0m13:45:23.920103 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5178BD250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E516C3BE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E51574F750>]}


============================== 13:45:23.934066 | 97afba3c-74ea-4f82-a245-ebe59971e4da ==============================
[0m13:45:23.934066 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:45:23.937057 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run-operation generate_faker_model', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:45:24.755229 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '97afba3c-74ea-4f82-a245-ebe59971e4da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E519085490>]}
[0m13:45:24.776115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '97afba3c-74ea-4f82-a245-ebe59971e4da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5190ADE50>]}
[0m13:45:24.778081 [info ] [MainThread]: Registered adapter: bigquery=1.6.1
[0m13:45:24.866907 [debug] [MainThread]: checksum: 5068fe71dce20d17d52958fa9cd93ea8f20705f4dc29725ea3e5886531e90d9e, vars: {}, profile: , target: , version: 1.6.17
[0m13:45:25.382520 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:45:25.382520 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:45:25.384487 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.answers
- models.answers.marts
- tests.answers
[0m13:45:25.395485 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '97afba3c-74ea-4f82-a245-ebe59971e4da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E517DCFAD0>]}
[0m13:45:25.441352 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '97afba3c-74ea-4f82-a245-ebe59971e4da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E519AC2B10>]}
[0m13:45:25.444333 [info ] [MainThread]: Found 1 operation, 1 source, 0 exposures, 0 metrics, 744 macros, 0 groups, 0 semantic models
[0m13:45:25.446322 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '97afba3c-74ea-4f82-a245-ebe59971e4da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E517866C10>]}
[0m13:45:25.451307 [debug] [MainThread]: Acquiring new bigquery connection 'macro_generate_faker_model'
[0m13:45:25.483226 [info ] [MainThread]: dbt_faker appended to `configured_sources`: source.Dummy_generated.fake_tpch.orders
[0m13:45:25.485219 [info ] [MainThread]: dbt_faker has some sources to fake!
[0m13:45:25.503171 [debug] [MainThread]: Command `dbt run-operation` succeeded at 13:45:25.502171 after 1.65 seconds
[0m13:45:25.504166 [debug] [MainThread]: Connection 'macro_generate_faker_model' was properly closed.
[0m13:45:25.508157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E518620250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E5186230D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E519AC3350>]}
[0m13:45:25.511152 [debug] [MainThread]: Flushing usage events
[0m13:46:20.209431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F9091BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F9090E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F9093E10>]}


============================== 13:46:20.219594 | d853357d-41fb-49cc-b338-e18154787e21 ==============================
[0m13:46:20.219594 [info ] [MainThread]: Running with dbt=1.6.17
[0m13:46:20.221588 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:/Users/fajlh/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\fajlh\\OneDrive\\Documents\\DBT_demo\\DBT_demo\\Dummy_generated\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run -m dbt_faker.py', 'send_anonymous_usage_stats': 'True'}
[0m13:46:20.884492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd853357d-41fb-49cc-b338-e18154787e21', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176FAA92150>]}
[0m13:46:20.903439 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd853357d-41fb-49cc-b338-e18154787e21', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176FAADEBD0>]}
[0m13:46:20.905434 [info ] [MainThread]: Registered adapter: bigquery=1.6.1
[0m13:46:20.971674 [debug] [MainThread]: checksum: 5068fe71dce20d17d52958fa9cd93ea8f20705f4dc29725ea3e5886531e90d9e, vars: {}, profile: , target: , version: 1.6.17
[0m13:46:21.390564 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m13:46:21.391563 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m13:46:21.392559 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.answers.marts
- models.answers
- tests.answers
[0m13:46:21.402532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'd853357d-41fb-49cc-b338-e18154787e21', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176FB401C10>]}
[0m13:46:21.439407 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'd853357d-41fb-49cc-b338-e18154787e21', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176FB2CEA10>]}
[0m13:46:21.440402 [info ] [MainThread]: Found 1 operation, 1 source, 0 exposures, 0 metrics, 744 macros, 0 groups, 0 semantic models
[0m13:46:21.442398 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'd853357d-41fb-49cc-b338-e18154787e21', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F4822790>]}
[0m13:46:21.445389 [warn ] [MainThread]: The selection criterion 'dbt_faker.py' does not match any nodes
[0m13:46:21.448382 [info ] [MainThread]: 
[0m13:46:21.453368 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m13:46:21.456359 [debug] [MainThread]: Command end result
[0m13:46:21.492264 [debug] [MainThread]: Command `dbt run` succeeded at 13:46:21.491275 after 1.33 seconds
[0m13:46:21.493261 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F95CDD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F95CD150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000176F8452D50>]}
[0m13:46:21.495255 [debug] [MainThread]: Flushing usage events
